#!/usr/bin/env bash
# shellcheck disable=SC1117,SC2034,SC2154

################################################################################

if [[ -n "${SCRIPT_DEBUG}" ]] ; then
  set -x
fi

################################################################################

# Utility name
APP="WEB Utils"

# Utility version
VER="2.4.0"

################################################################################

NORM=0
BOLD=1
ITLC=3
UNLN=4
RED=31
GREEN=32
YELLOW=33
BLUE=34
MAG=35
CYAN=36
GREY=37
DARK=90

CL_NORM="\e[${NORM}m"
CL_BOLD="\e[${BOLD}m"
CL_ITLC="\e[${ITLC}m"
CL_UNLN="\e[${UNLN}m"
CL_RED="\e[${RED}m"
CL_GREEN="\e[${GREEN}m"
CL_YELLOW="\e[${YELLOW}m"
CL_BLUE="\e[${BLUE}m"
CL_MAG="\e[${MAG}m"
CL_CYAN="\e[${CYAN}m"
CL_GREY="\e[${GREY}m"
CL_DARK="\e[${DARK}m"
CL_BL_RED="\e[${BOLD};${RED}m"
CL_BL_GREEN="\e[${BOLD};${GREEN}m"
CL_BL_YELLOW="\e[${BOLD};${YELLOW}m"
CL_BL_BLUE="\e[${BOLD};${BLUE}m"
CL_BL_MAG="\e[${BOLD};${MAG}m"
CL_BL_CYAN="\e[${BOLD};${CYAN}m"
CL_BL_GREY="\e[${BOLD};${GREY}m"
CL_IT_DARK="\e[${ITLC};${DARK}m"

################################################################################

# Pattern used for generating temporary files and directories (String)
TMP_PATTERN="/tmp/_wu.XXXXXXXXX"

# Default RSA key length (Number)
RSA_SIZE=2048

# Default ECC key length (Number)
ECC_SIZE=256

# Minimal RSA size (Number)
MIN_RSA_SIZE=2048

# Maximum RSA size (Number)
MAX_RSA_SIZE=8192

# Minimal ECC size (Number)
MIN_ECC_SIZE=256

# Maximum ECC size (Number)
MAX_ECC_SIZE=384

################################################################################

SUPPORTED_OPTS="!ecc size !help !version !no_color"
SHORT_OPTS="E:!ecc s:size h:!help v:!version nc:!no_color"

################################################################################

# Main functions
#
# *: All arguments passed to script
#
# Code: No
# Echo: No
main() {
  if [[ -n "$no_color" || -n "$NO_COLOR" ]] || [[ ! -c /dev/stdout && -z $FAKETTY ]] ; then
    unset NORM BOLD CL_ITLC UNLN RED GREEN YELLOW BLUE MAG CYAN GREY DARK
    unset CL_NORM CL_BOLD CL_UNLN CL_RED CL_GREEN CL_YELLOW CL_BLUE CL_MAG CL_CYAN CL_GREY CL_DARK
    unset CL_BL_RED CL_BL_GREEN CL_BL_YELLOW CL_BL_BLUE CL_BL_MAG CL_BL_CYAN CL_BL_GREY CL_IT_DARK
    no_color=true
  fi

  if [[ -n "$version" ]] ; then
    about
    exit 0
  fi

  if [[ $# -eq 0 || -n "$help" ]] ; then
    usage
    exit 0
  fi

  trap sigExitTrap SIGINT SIGQUIT SIGTERM

  local cmd="$1"

  shift 1

  case $cmd in
    "csr-gen")        genCSR "$@" ;;
    "csr-info")       showCSR "$@" ;;
    "csr-config-gen") genCSRConfig "$@" ;;
    "crt-info")       showCRT "$@" ;;
    "self-signed")    genSelfSigned "$@" ;;
    "hpkp-gen")       genHPKPHeader "$@" ;;
    "ocsp-gen")       genOCSP "$@" ;;
    "ocsp-check")     checkOCSP "$@" ;;
    "0rtt-check")     checkRTT "$@" ;;
    "htpasswd")       genHTPasswd "$@" ;;
    *) error "Unknown command ${CL_BL_RED}${cmd}${CL_RED}"
       doExit 1 ;;
  esac

  doExit $?
}

# Generate signing request
#
# 1: Domain or config file (String)
#
# Code: No
# Echo: No
genCSR() {
  local domainOrCfg="$1"

  if [[ -z "$domainOrCfg" ]] ; then
    usage
    return 0
  fi

  if [[ -e "$domainOrCfg" && -r "$domainOrCfg" ]] ; then
    generateCRSFromConfig "$@"
    return $?
  fi

  generateCRSInteractive "$@"
  return $?
}


# Print info about CSR file
#
# 1: CSR file (String)
#
# Code: Yes
# Echo: No
showCSR() {
  local csr="$1"

  if [[ -z "$csr" ]] ; then
    usage
    return 0
  fi

  if [[ ! -e "$csr" ]] ; then
    error "CSR file ${CL_BL_RED}${csr}${CL_RED} does not exist"
    return 1
  fi

  if [[ ! -r "$csr" ]] ; then
    error "CSR file ${CL_BL_RED}${csr}${CL_RED} is not readable"
    return 1
  fi

  if ! grep -q '\-BEGIN CERTIFICATE REQUEST\-' "$csr" ; then
    error "${CL_BL_RED}${csr}${CL_RED} is not a certificate signing request file"
    return 1
  fi

  local tmp_file subject country state city company section domain email
  local algorithm key_size key_info

  tmp_file=$(createTempFile)

  if ! openssl req -noout -text -in "$csr" > "$tmp_file" ; then
    error "Error while reading CSR file"
    return 1
  fi

  subject=$(grep 'Subject:' "$tmp_file" | sed 's/^ *Subject: //' | sed 's/ = /=/g' | sed 's/, /,/g' | tr '/' ',')
  country=$(echo "$subject" | cut -f1 -d',' | cut -f2 -d'=')
  state=$(echo "$subject" | cut -f2 -d',' | cut -f2 -d'=')
  city=$(echo "$subject" | cut -f3 -d',' | cut -f2 -d'=')
  company=$(echo "$subject" | cut -f4 -d',' | cut -f2 -d'=')
  section=$(echo "$subject" | cut -f5 -d',' | cut -f2 -d'=')
  domain=$(echo "$subject" | cut -f6 -d',' | cut -f2 -d'=')
  email=$(echo "$subject" | cut -f7 -d',' | cut -f2 -d'=')
  key_algo=$(grep 'Public Key Algorithm:' "$tmp_file" | cut -f2 -d':' | tr -d ' ')
  key_size=$(grep 'Public-Key:' "$tmp_file" | cut -f2 -d':')

  if [[ "$key_algo" == "id-ecPublicKey" ]] ; then
    key_info="ECC${CL_GREY}${key_size}${CL_NORM}"
  else
    key_info="RSA${CL_GREY}${key_size}${CL_NORM}"
  fi

  show ""
  show " ${CL_BOLD}Key:${CL_NORM}                   ${key_info:-—}"
  show " ${CL_BOLD}Common name (domain):${CL_NORM}  ${domain:-—}"
  show " ${CL_BOLD}Email address:${CL_NORM}         ${email:-—}"
  show " ${CL_BOLD}Country code:${CL_NORM}          ${country:-—}"
  show " ${CL_BOLD}State or province:${CL_NORM}     ${state:-—}"
  show " ${CL_BOLD}Locality:${CL_NORM}              ${city:-—}"
  show " ${CL_BOLD}Organization:${CL_NORM}          ${company:-—}"
  show " ${CL_BOLD}Organizational unit:${CL_NORM}   ${section:-—}"
  show ""

  return 0
}

# Show information from CRT file
#
# 1: Path to CRT file (String)
#
# Code: Yes
# Echo: No
showCRT() {
  local crt="$1"

  if [[ -z "$crt" ]] ; then
    usage
    return 0
  fi

  if [[ ! -e "$crt" ]] ; then
    error "CRT file ${CL_BL_RED}${crt}${CL_RED} does not exist"
    return 1
  fi

  if [[ ! -r "$crt" ]] ; then
    error "CRT file ${CL_BL_RED}${crt}${CL_RED} is not readable"
    return 1
  fi

  if ! grep -q '\-BEGIN CERTIFICATE\-' "$crt" ; then
    error "${CL_BL_RED}${crt}${CL_RED} is not a certificate file"
    return 1
  fi

  local tmp_file issuer subject alt_names
  local sig_algo key_algo key_size
  local valid_before valid_after valid_after_dt valid_before_dt
  local now valid_before_ts valid_days

  tmp_file=$(createTempFile)

  if ! openssl x509 -text -noout -in "$crt" > "$tmp_file" ; then
    error "Error while reading CRT file"
    return 1
  fi

  subject=$(grep 'Subject:' "$tmp_file" | head -1 | sed 's/ = /=/g' | cut -f2 -d':' | sed 's/^ \+//' | sed 's/, / \/ /g' | sed 's/\w\w\?=//g')
  issuer=$(grep 'Issuer:' "$tmp_file" | head -1 | sed 's/ = /=/g' | cut -f2 -d':' | sed 's/^ \+//' | sed 's/, / \/ /g' | sed 's/\w\w\?=//g')
  alt_names=$(grep -A1 'Subject Alternative Name:' "$tmp_file" | tail -1 | sed 's/^ \+//' | sed 's/DNS://g' | tr -d ',')
  valid_after=$(grep 'Not Before:' "$tmp_file" | cut -f2-99 -d':' | sed 's/^ \+//')
  valid_before=$(grep 'Not After :' "$tmp_file" | cut -f2-99 -d':' | sed 's/^ \+//')
  sig_algo=$(grep 'Signature Algorithm:' "$tmp_file" | head -1 | cut -f2 -d':' | sed 's/^ \+//')
  key_algo=$(grep 'Public Key Algorithm:' "$tmp_file" | cut -f2 -d':' | sed 's/^ \+//')
  key_size=$(grep 'Public-Key:' "$tmp_file" | cut -f2 -d':')

  if [[ "$key_algo" == "id-ecPublicKey" ]] ; then
    key_info="ECC${CL_GREY}${key_size}${CL_NORM}"
  else
    key_info="RSA${CL_GREY}${key_size}${CL_NORM}"
  fi

  now=$(date +'%s')
  valid_after_dt=$(date --date="$valid_after" +'%Y/%m/%d %H:%M')
  valid_before_dt=$(date --date="$valid_before" +'%Y/%m/%d %H:%M')
  valid_before_ts=$(date --date="$valid_before" +'%s')
  valid_days=$(( (valid_before_ts - now) / 86400 ))

  if [[ $valid_days -ge 0 ]] ; then
    valid_before_dt="$valid_before_dt ${CL_GREY}($valid_days days)${CL_NORM}"
  fi

  show ""
  show " ${CL_BOLD}Key:${CL_NORM}                  ${key_info:-—}"
  show " ${CL_BOLD}Subject:${CL_NORM}              ${subject:-—}"
  show " ${CL_BOLD}Alt Names:${CL_NORM}            ${alt_names:-—}"
  show " ${CL_BOLD}Issuer:${CL_NORM}               ${issuer:-—}"
  show " ${CL_BOLD}Signature Algorithm:${CL_NORM}  ${sig_algo:-—}"
  show " ${CL_BOLD}Valid after:${CL_NORM}          ${valid_after_dt:-—}"
  show " ${CL_BOLD}Valid before:${CL_NORM}         ${valid_before_dt:-—}"
  show ""

  return 0
}

# Generate self-signed certificate
#
# 1: Variable Description (Type)
#
# Code: No
# Echo: No
genSelfSigned() {
  local domain="$1"

  if [[ -z "$domain" ]] ; then
    usage
    return 0
  fi

  local file_name subject

  file_name=$(getFileName "$domain")
  subject="/C=JP/ST=Tokyo/L=Tokyo/O=SELFSIGN/OU=IT/CN=$domain"

  if [[ -z "$ecc" ]] ; then
    if ! openssl req -x509 -newkey "rsa:${size:-$RSA_SIZE}" -keyout "$file_name.key" -out "$file_name.crt" -sha256 -days 21 -nodes -subj "$subject" &> /dev/null ; then
      error "Error while certificate generation"
      return 1
    fi
  else
    if ! openssl ecparam -name "$(getECCCurveName)" -genkey -out "${file_name}.key" &> /dev/null ; then
      error "Error while key generation"
      return 1
    fi

    if ! openssl req -x509 -key "${file_name}.key" -out "${file_name}.crt" -days 21 -subj "$subject" &> /dev/null ; then
      error "Error while certificate generation"
      return 1
    fi
  fi

  chmod 600 "${file_name}.key" "${file_name}.crt"

  show "Self-signed certificate successfully generated as ${file_name}.crt (key: ${file_name}.key)" $GREEN

  return 0
}

# Generate OpenSSL config for CSR generation
#
# 1: Domain (String)
#
# Code: Yes
# Echo: No
genCSRConfig() {
  local domain="$1"
  local host tmp_file domain email country state city company section

  if [[ -z "$domain" ]] ; then
    usage
    return 0
  fi

  host=$(getFileName "$1")
  tmp_file=$(createTempFile)

  createOpenSSLConfigTemplate "$tmp_file"

  show ""

  read -r -e -p "Email Address: " email
  read -r -e -p "Country Code (XX): " country
  read -r -e -p "State or Province: " state
  read -r -e -p "Locality (city): " city
  read -r -e -p "Organization (company): " company
  read -r -e -p "Organizational Unit (section): " section

  sed -i "s/%DOMAIN%/$domain/" "$tmp_file"
  sed -i "s/%EMAIL%/$email/" "$tmp_file"
  sed -i "s/%COUNTRY%/$country/" "$tmp_file"
  sed -i "s/%STATE%/$state/" "$tmp_file"
  sed -i "s/%CITY%/$city/" "$tmp_file"
  sed -i "s/%COMPANY%/$company/" "$tmp_file"
  sed -i "s/%SECTION%/$section/" "$tmp_file"

  show ""

  cat "$tmp_file" > "${host}.cnf"
  chmod 0600 "${host}.cnf"

  show "Configuration file created as ${host}.cnf" $GREEN

  return 0
}

# Generate OCSP
#
# 1: Server cert or cert chain file (String)
# 2: Issuer cert (String) [Optional]
#
# Code: No
# Echo: No
genOCSP() {
  if [[ $# -eq 0 ]] ; then
    usage
    return 0
  fi

  local issuer_cert server_cert output

  if [[ ! -f "$1" ]] ; then
    error "File ${CL_BL_RED}${1}${CL_RED} does not exist"
    return 1
  fi

  if isChain "$1" ; then
    server_cert=$(extractCertFromChain "$1" 1)
    issuer_cert=$(extractCertFromChain "$1" 2)
    output=$(echo "$1" | sed 's/-chain//' | sed 's/.crt/.ocsp/')
  else
    server_cert="$1"
    issuer_cert="$2"
    output="${1/.crt/.ocsp}"
  fi

  if [[ ! -f "$server_cert" ]] ; then
    error "Server certificate file ${CL_BL_RED}${server_cert}${CL_RED} is not exist"
    return 1
  fi

  if [[ ! -f "$issuer_cert" ]] ; then
    error "Issuer certificate file ${CL_BL_RED}${issuer_cert}${CL_RED} is not exist"
    return 1
  fi

  generateOCSPFile "$issuer_cert" "$server_cert" "$output"

  return $?
}

# Check OCSP stapling
#
# 1: Host (String)
# 2: Server name (String) [Optional]
#
# Code: No
# Echo: No
checkOCSP() {
  if [[ $# -eq 0 ]] ; then
    usage
    return 0
  fi

  local domain="$1"
  local server_name="${2:-$domain}"

  local tmp_file

  tmp_file=$(createTempFile)

  openssl s_client -servername "$server_name" -connect "$domain:443" -tls1 -tlsextdebug -status 2>&1 < /dev/null &> "$tmp_file"

  if ! grep -q 'OCSP Response Status: successful' "$tmp_file" ; then
    rm -f "$tmp_file" &> /dev/null
    show "OCSP Response Status: ${CL_RED}No response sent${CL_NORM}"
    return 1
  fi

  show "OCSP Response Status: ${CL_GREEN}Success${CL_NORM}"
  grep -A 14 'OCSP Response Data:' "$tmp_file"

  rm -f "$tmp_file" &> /dev/null

  return 0
}

# Checks 0-RTT support
#
# 1: Domain (String)
# 2: Server name (String) [Optional]
#
# Code: Yes
# Echo: No
checkRTT() {
  if [[ $# -eq 0 ]] ; then
    usage
    return 0
  fi

  if ! isProtocolSupported "TLSv1.3" ; then
    error "Installed OpenSSL version doesn't support TLS 1.3"
    return 1
  fi

  local domain="$1"
  local server_name="${2:-$domain}"

  local req_temp ses_temp

  req_temp=$(createTempFile)
  ses_temp=$(createTempFile)

  echo -e "GET / HTTP/1.1\r\nHost: ${server_name}\r\nConnection: close\r\n\r\n" > "$req_temp"

  openssl s_client -servername "$server_name" -connect "${domain}:443" -tls1_3 -sess_out "$ses_temp" -ign_eof < "$req_temp" &> /dev/null

  sleep 0.1

  status=$(openssl s_client -servername "$server_name" -connect "${domain}:443" -tls1_3 -sess_in "$ses_temp" -early_data "$req_temp" <<< "Q" 2>&1 | grep 'Early data was ')

  if [[ "$status" == "Early data was accepted" ]] ; then
    show "0-RTT Status: ${CL_GREEN}$status${CL_NORM}"
  else
    show "0-RTT Status: ${CL_RED}${status:-Not supported}${CL_NORM}"
  fi

  rm -f "$req_temp" "$ses_temp" &> /dev/null

  return 0
}

# Generate record with MD5 password hash for .htpasswd
#
# 1: User name (String)
# 2: Password (String)
#
# Code: No
# Echo: No
genHTPasswd() {
  if [[ $# -ne 2 ]] ; then
    usage
    return 1
  fi

  local user="$1"
  local password="$2"

  echo "$user:$(openssl passwd -apr1 "$password")"
}

# Generate HPKP for some request
#
# 1: Path to csr file (String)
#
# Code: Yes
# Echo: No
genHPKPHeader() {
  if [[ $# -ne 2 ]] ; then
    usage
    return 0
  fi

  local main_file="$1"
  local backup_file="$2"

  if [[ ! -r "$main_file" ]] ; then
    error "File ${CL_BL_RED}${main_file}${CL_RED} is not readable"
    return 1
  fi

  local main_pin backup_pin

  main_pin=$(generateHPKHHash "$main_file")

  if [[ -n "$backup_file" ]] ; then
    backup_pin=$(generateHPKHHash "$backup_file")
  fi

  if [[ -z "$main_pin" ]] ; then
    error "Can't generate HPKP for given request"
    return 1
  fi

  show "\n${CL_BL_GREEN}HPKP Header successfully generated!${CL_GREEN} Add this header as part of your config file.${CL_NORM}"

  if [[ -z "$backup_pin" ]] ; then
    show "\nadd_header Public-Key-Pins 'pin-sha256=\"$main_pin\";max-age=86400';\n"
  else
    show "\nadd_header Public-Key-Pins 'pin-sha256=\"$main_pin\";pin-sha256=\"$backup_pin\";max-age=86400';\n"
  fi

  show "More info: https://developer.mozilla.org/en-US/docs/Web/Security/Public_Key_Pinning\n" $DARK

  return 0
}

################################################################################

# Generate OCSP file
#
# 1: Path to server certificate (String)
# 2: Path to issuer certificate (String)
# 3: Output name (String)
#
# Code: Yes
# Echo: No
generateOCSPFile() {
  if [[ $# -ne 3 ]] ; then
    usage
    return 0
  fi

  local issuer_cert="$1"
  local server_cert="$2"
  local output="$3"

  local url

  url=$(openssl x509 -in "$server_cert" -text | grep "OCSP - URI:" | cut -d: -f2,3)

  if ! openssl ocsp -noverify -no_nonce -respout "$output" -issuer "$issuer_cert" -cert "$server_cert" -url "$url" &> /dev/null ; then
    error "Error while OCSP stapling file generation"
    return 1
  fi

  chmod 600 "$output"

  show "OCSP stapling file saved as $output" $GREEN

  return 0
}

# Generate CSR based on info from given OpenSSL configuration file
#
# 1: Path to configuration file (String)
#
# Code: Yes
# Echo: No
generateCRSFromConfig() {
  local config="$1"
  local domain file_name

  if ! checkKeyLength ; then
    return 1
  fi

  domain=$(grep 'DOMAIN = ' "$config" | cut -f2 -d'=' | tr -d ' "')

  if [[ -z "$domain" ]] ; then
    error "Can't read domain from configuration file"
    return 1
  fi

  file_name=$(getFileName "$domain")

  if [[ -z "$ecc" ]] ; then
    if ! openssl req -new -config "$config" -newkey "rsa:${size:-$RSA_SIZE}" -nodes -sha256 -keyout "${file_name}.key" -out "${file_name}.csr" &> /dev/null ; then
      error "Error while CSR file generation"
      return 1
    fi
  else
    if ! openssl ecparam -name "$(getECCCurveName)" -genkey -out "${file_name}.key" &> /dev/null ; then
      error "Error while key generation for CSR file"
      return 1
    fi

    if ! openssl req -new -config "$config" -key "${file_name}.key" -out "${file_name}.csr" &> /dev/null ; then
      error "Error while CSR file generation"
      return 1
    fi
  fi

  chmod 600 "${file_name}.key" "${file_name}.csr"

  show "Certificate Signing Request successfully generated as ${file_name}.csr (key: ${file_name}.key)" $GREEN

  return 0
}

# Generate CSR in interactive mode
#
# 1: Domain (String)
#
# Code: Yes
# Echo: No
generateCRSInteractive() {
  local domain="$1"
  local file_name

  if ! checkKeyLength ; then
    return 1
  fi

  file_name=$(getFileName "$1")

  if [[ -z "$ecc" ]] ; then
    if ! openssl req -new -newkey "rsa:${size:-$RSA_SIZE}" -nodes -sha256 -keyout "${file_name}.key" -out "${file_name}.csr" ; then
      error "Error while CSR file generation"
      return 1
    fi
  else
    if ! openssl ecparam -name "$(getECCCurveName)" -genkey -out "${file_name}.key" ; then
      error "Error while key generation for CSR file"
      return 1
    fi

    if ! openssl req -new -key "${file_name}.key" -out "${file_name}.csr" ; then
      error "Error while CSR file generation"
      return 1
    fi
  fi

  chmod 600 "${file_name}.key" "${file_name}.csr"

  show ""
  show "Certificate Signing Request successfully generated as ${file_name}.csr (key: ${file_name}.key)" $GREEN

  return 0
}

# Generate HPKP hash from given file
#
# 1: Key / CRT / CSR file
#
# Code: No
# Echo: Hash (String)
generateHPKHHash() {
  local file="$1"

  if [[ "$file" == *.key ]] ; then
    openssl rsa -in "$file" -outform der -pubout 2>/dev/null | openssl dgst -sha256 -binary | openssl enc -base64
  elif [[ "$file" == *.csr ]] ; then
    openssl req -in "$file" -pubkey -noout 2>/dev/null | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -binary | openssl enc -base64
  elif [[ "$file" == *.crt ]] ; then
    openssl x509 -in "$file" -pubkey -noout 2>/dev/null | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -binary | openssl enc -base64
  else
    echo ""
  fi
}

# Check if given file is chain
#
# 1: Path to file (String)
#
# Code: Yes
# Echo: No
isChain() {
  local file="$1"

  if [[ ! -f $file ]] ; then
    return 1
  fi

  if ! grep -q "BEGIN CERTIFICATE" "$file" ; then
    return 1
  fi

  return 0
}

# Extract certificate from chain to file
#
# 1: Path to chain file (String)
# 2: Number of certificate in chain (Number)
#
# Code: No
# Echo: Path to temporary file with certificate (String)
extractCertFromChain() {
  local chain cert_num cert_start cert_end tmp_file

  chain="$1"
  cert_num="$2"

  cert_start=$(grep -n "BEGIN CERTIFICATE" "$chain" | cut -f1 -d: | sed -n "${cert_num}p")
  cert_end=$(grep -n "END CERTIFICATE" "$chain" | cut -f1 -d: | sed -n "${cert_num}p")

  if [[ -z "$cert_start" || -z "$cert_end" ]] ; then
    return
  fi

  tmp_file=$(createTempFile)

  sed -n "${cert_start},${cert_end}p" < "$chain" > "$tmp_file"

  echo "$tmp_file"
}

# Create OpenSSL configuration file template
#
# 1: Path to file (String)
#
# Code: No
# Echo: No
createOpenSSLConfigTemplate() {
  local file="$1"

cat << EOF > "$file"
# ############################################################################ #
#                OpenSSL configuration file for CSR generation                 #
# ############################################################################ #

# Common Name (eg, your name or your server's hostname)
DOMAIN = "%DOMAIN%"

# Email Address
EMAIL = "%EMAIL%"

# Country Name (2 letter code)
COUNTRY = "%COUNTRY%"

# State or Province Name (full name)
STATE = "%STATE%"

# Locality Name (eg, city)
CITY = "%CITY%"

# Organization Name (eg, company)
COMPANY = "%COMPANY%"

# Organizational Unit Name (eg, section)
SECTION = "%SECTION%"

# ##################### NO MODIFICATIONS REQUIRED BELOW ###################### #

[ req ]
prompt = no
encrypt_key = no
distinguished_name = dn

[ dn ]
C = \$COUNTRY
ST = \$STATE
L = \$CITY
O = \$COMPANY
OU = \$SECTION
CN = \$DOMAIN
emailAddress = \$EMAIL

EOF
}

# Formats host name
#
# 1: Domain name (String)
#
# Code: No
# Echo: Formatted name for file (String)
getFileName() {
  echo "$1" | sed 's/\*\./wildcard-/g' | sed 's/\./_/g'
}

# Check for key size
#
# Code: Yes
# Echo: No
checkKeyLength() {
  if [[ -z "$size" ]] ; then
    return 0
  fi

  if [[ -n "$ecc" && $size -lt $MIN_ECC_SIZE ]] ; then
    error "ECC key size is too small ($size < $MIN_ECC_SIZE)"
    return 1
  fi

  if [[ -n "$ecc" && $size -gt $MAX_ECC_SIZE ]] ; then
    error "ECC key size is too big ($size > $MAX_ECC_SIZE)"
    return 1
  fi

  if [[ -z "$ecc" && $size -lt $MIN_RSA_SIZE ]] ; then
    error "RSA key size is too small ($size < $MIN_RSA_SIZE)"
    return 1
  fi

  if [[ -z "$ecc" && $size -gt $MAX_RSA_SIZE ]] ; then
    error "RSA key size is too big ($size > $MAX_RSA_SIZE)"
    return 1
  fi

  return 0
}

# Returns curve name for ECC certificate
#
# Code: No
# Echo: Curve name (String)
getECCCurveName() {
  if [[ "$size" == "384" ]] ; then
    echo "secp384r1"
  else
    echo "prime256v1"
  fi
}

# Check if installed OpenSSL version supports given protocol
#
# 1: Protocol (String)
#
# Code: Yes
# Echo: No
isProtocolSupported() {
  openssl ciphers -v | tr -s " " | cut -f2 -d" " | grep -q "$1"
  return $?
}

# Create temporary file
#
# Code: No
# Echo: Yes
createTempFile() {
  local tmp_file

  tmp_file=$(mktemp "$TMP_PATTERN")
  chmod 0600 "$tmp_file"

  echo "$tmp_file"
}

# INT/TERM signal handler
#
# Code: No
# Echo: No
sigExitTrap() {
  doExit 1
}

# Remove temporary data and exit with given exit code
#
# 1: Exit code (Number) [Optional]
#
# Code: No
# Echo: No
doExit() {
  local ec="${1:-0}"

  rm -f ${TMP_PATTERN//X/}*

  exit "$ec"
}

################################################################################

# Show message
#
# 1: Message (String)
# 2: Message color (Number) [Optional]
#
# Code: No
# Echo: No
show() {
  if [[ -n "$2" && -z "$no_color" ]] ; then
    echo -e "\e[${2}m${1}\e[0m"
  else
    echo -e "$*"
  fi
}

# Print error message
#
# 1: Message (String)
# 2: Message color (Number) [Optional]
#
# Code: No
# Echo: No
error() {
  show "$@" $RED 1>&2
}

# Print usage info
#
# Code: No
# Echo: No
usage() {
  show ""
  show "${CL_BOLD}Usage:${CL_NORM} web-utils ${CL_YELLOW}command${CL_NORM} ${CL_GREY}args…${CL_NORM}"
  show ""
  show "Commands" $BOLD
  show ""

  if [[ -n "$DARK" ]] ; then
    show "${CL_DARK}┌ ${CL_YELLOW}csr-gen${CL_NORM} ${CL_GREY}domain${CL_NORM} ${CL_DARK}....................${CL_NORM} Generate key and a certificate signing request"
    show "${CL_DARK}└ ${CL_YELLOW}csr-gen${CL_NORM} ${CL_GREY}config${CL_NORM} ${CL_DARK}....................${CL_NORM} Generate key and a certificate signing request from OpenSSL configuration file"
    show "  ${CL_YELLOW}csr-info${CL_NORM} ${CL_GREY}csr${CL_NORM} ${CL_DARK}......................${CL_NORM} Print info from certificate signing request"
    show "  ${CL_YELLOW}csr-config-gen${CL_NORM} ${CL_GREY}domain${CL_NORM} ${CL_DARK}.............${CL_NORM} Generate OpenSSL configuration file for certificate signing request generation"
    show "  ${CL_YELLOW}crt-info${CL_NORM} ${CL_GREY}crt${CL_NORM} ${CL_DARK}......................${CL_NORM} Print info from certificate"
    show "  ${CL_YELLOW}self-signed${CL_NORM} ${CL_GREY}domain${CL_NORM} ${CL_DARK}................${CL_NORM} Generate self-signed certificate"
    show "${CL_DARK}┌ ${CL_YELLOW}hpkp-gen${CL_NORM} ${CL_GREY}csr backup${CL_NORM} ${CL_DARK}...............${CL_NORM} Generate HTTP public key pinning (HPKP) header from CSR file"
    show "${CL_DARK}│ ${CL_YELLOW}hpkp-gen${CL_NORM} ${CL_GREY}key backup${CL_NORM} ${CL_DARK}...............${CL_NORM} Generate HTTP public key pinning (HPKP) header from KEY file"
    show "${CL_DARK}└ ${CL_YELLOW}hpkp-gen${CL_NORM} ${CL_GREY}crt backup${CL_NORM} ${CL_DARK}...............${CL_NORM} Generate HTTP public key pinning (HPKP) header from CRT file"
    show "${CL_DARK}┌ ${CL_YELLOW}ocsp-gen${CL_NORM} ${CL_GREY}server-cert${CL_NORM} ${CL_GREY}issuer-cert${CL_NORM} ${CL_DARK}..${CL_NORM} Generate OCSP stapling file from server certificate"
    show "${CL_DARK}└ ${CL_YELLOW}ocsp-gen${CL_NORM} ${CL_GREY}cert-chain${CL_NORM} ${CL_DARK}...............${CL_NORM} Generate OCSP stapling file from server certificate chain"
    show "  ${CL_YELLOW}ocsp-check${CL_NORM} ${CL_GREY}domain${CL_NORM} ${CL_DARK}server-name${CL_NORM} ${CL_DARK}.....${CL_NORM} Check OCSP response status for some host"
    show "  ${CL_YELLOW}0rtt-check${CL_NORM} ${CL_GREY}domain${CL_NORM} ${CL_DARK}server-name${CL_NORM} ${CL_DARK}.....${CL_NORM} Check 0-RTT support"
    show "  ${CL_YELLOW}htpasswd${CL_NORM} ${CL_GREY}user password${CL_NORM} ${CL_DARK}............${CL_NORM} Generate record with MD5 password hash for .htpasswd files"
  else
    show "┌ csr-gen domain                      Generate key and a certificate signing request"
    show "└ csr-gen config                      Generate key and a certificate signing request from OpenSSL configuration file"
    show "  csr-info csr                        Print info from certificate signing request"
    show "  csr-config-gen domain               Generate OpenSSL configuration file for certificate signing request generation"
    show "  crt-info crt                        Print info from certificate"
    show "  self-signed domain                  Generate self-signed certificate"
    show "┌ hpkp-gen csr backup                 Generate HTTP public key pinning (HPKP) header from CSR file"
    show "│ hpkp-gen key backup                 Generate HTTP public key pinning (HPKP) header from KEY file"
    show "└ hpkp-gen crt backup                 Generate HTTP public key pinning (HPKP) header from CRT file"
    show "┌ ocsp-gen server-cert issuer-cert    Generate OCSP stapling file from server certificate"
    show "└ ocsp-gen cert-chain                 Generate OCSP stapling file from server certificate chain"
    show "  ocsp-check domain server-name       Check OCSP response status for some host"
    show "  0rtt-check domain server-name       Check 0-RTT support"
    show "  htpasswd user password              Generate record with MD5 password hash for .htpasswd files"
  fi

  show ""
  show "Options" $BOLD
  show ""

  if [[ -n "$DARK" ]] ; then
    show "  ${CL_GREEN}--ecc, -E${CL_NORM} ${CL_DARK}........${CL_NORM} Generate ECC certificate"
    show "  ${CL_GREEN}--size, -S ${CL_GREY}size${CL_NORM} ${CL_DARK}..${CL_NORM} Key size ${CL_DARK}(ECC: $MIN_ECC_SIZE-$MAX_ECC_SIZE / RSA: $MIN_RSA_SIZE-$MAX_RSA_SIZE)${CL_NORM}"
    show "  ${CL_GREEN}--no-color, -nc${CL_NORM} ${CL_DARK}..${CL_NORM} Disable colors in output"
    show "  ${CL_GREEN}--help, -h${CL_NORM} ${CL_DARK}.......${CL_NORM} Show this help message"
    show "  ${CL_GREEN}--version, -v${CL_NORM} ${CL_DARK}....${CL_NORM} Show information about version"
  else
    show "  --ecc, -E        Generate ECC certificate"
    show "  --size, -s size  Key size (ECC: $MIN_ECC_SIZE-$MAX_ECC_SIZE / RSA: $MIN_RSA_SIZE-$MAX_RSA_SIZE)"
    show "  --no-color, -nc  Disable colors in output"
    show "  --help, -h       Show this help message"
    show "  --version, -v    Show information about version"
  fi

  show ""
  show "Examples" $BOLD
  show ""
  show "  web-utils csr-gen domain.com"
  show "  ${CL_IT_DARK}Generate RSA key and a certificate signing request for domain.com${CL_NORM}"
  show ""
  show "  web-utils hpkp-gen domain.com.csr domain.com.backup.key"
  show "  ${CL_IT_DARK}Generate HTTP public key pinning (HPKP) header with server and backup pins${CL_NORM}"
  show ""
  show "  web-utils ocsp-gen sever.crt issuer.crt"
  show "  ${CL_IT_DARK}Generate OCSP stapling file using server and issuer certificates${CL_NORM}"
  show ""
  show "  web-utils ocsp-gen sever-chain.crt"
  show "  ${CL_IT_DARK}Generate OCSP stapling file using certificate chain${CL_NORM}"
  show ""
  show "  web-utils ocsp-check essentialkaos.com"
  show "  ${CL_IT_DARK}Check OCSP response status for essentialkaos.com${CL_NORM}"
  show ""
}

# Show info about version
#
# Code: No
# Echo: No
about() {
  local openssl_ver

  openssl_ver=$(openssl version 2>/dev/null | tr -s ' ' | cut -f2 -d' ')

  show ""
  show "${CL_BL_CYAN}$APP${CL_NORM} ${CL_CYAN}$VER${CL_NORM} - Helpers for working with web server"
  show "│" $DARK
  show "└ OpenSSL: ${openssl_ver:-—}" $DARK
  show ""
  show "Copyright (C) 2009-$(date +%Y) ESSENTIAL KAOS" $DARK
  show "Apache License, Version 2.0 <https://www.apache.org/licenses/LICENSE-2.0>" $DARK
  show ""
}

# Show warning message about unsupported option
#
# 1: Option name (String)
#
# Code: No
# Echo: No
showOptWarn() {
  error "Unknown option ${CL_BL_RED}${1}${CL_NORM}"
  exit 1
}

## OPTIONS PARSING 6 ###########################################################

if [[ $# -eq 0 ]] ; then
  main
fi

unset opt optn optm optv optt optk

optv="$*" ; optt=()

while [[ -n "$1" ]] ; do
  if [[ "$1" =~ \  && -n "$optn" ]] ; then
    declare "$optn=$1"

    unset optn && shift && continue
  elif [[ $1 =~ ^-{1}[a-zA-Z0-9]{1,2}+.*$ ]] ; then
    optm=${1:1}

    if [[ \ $SHORT_OPTS\  =~ \ $optm:!?([a-zA-Z0-9_]*) ]] ; then
      opt="${BASH_REMATCH[1]}"
    else
      declare -F showOptWarn &>/dev/null && showOptWarn "-$optm"
      shift && continue
    fi

    if [[ -z "$optn" ]] ; then
      optn=$opt
    else
      # shellcheck disable=SC2015
      [[ -z "$optk" ]] && ( declare -F showOptValWarn &>/dev/null && showOptValWarn "--$optn" ) || declare "$optn=true"
      optn=$opt
    fi

    if [[ ! $SUPPORTED_OPTS\  =~ !?$optn\  ]] ; then
      declare -F showOptWarn &>/dev/null && showOptWarn "-$optm"
      shift && continue
    fi

    if [[ ${BASH_REMATCH[0]:0:1} == "!" ]] ; then
      declare "$optn=true" ; unset optn ; optk=true
    else
      unset optk
    fi

    shift && continue
  elif [[ "$1" =~ ^-{2}[a-zA-Z]{1}[a-zA-Z0-9_-]+.*$ ]] ; then
    opt=${1:2}

    if [[ $opt == *=* ]] ; then
      IFS="=" read -ra opt <<< "$opt"

      optm="${opt[0]}" ; optm=${optm//-/_}

      if [[ ! $SUPPORTED_OPTS\  =~ $optm\  ]] ; then
        declare -F showOptWarn &>/dev/null && showOptWarn "--${opt[0]//_/-}"
        shift && continue
      fi

      # shellcheck disable=SC2015
      [[ -n "${!optm}" && $MERGEABLE_OPTS\  =~ $optm\  ]] && declare "$optm=${!optm} ${opt[*]:1:99}" || declare "$optm=${opt[*]:1:99}"

      unset optm && shift && continue
    else
      # shellcheck disable=SC2178
      opt=${opt//-/_}

      if [[ -z "$optn" ]] ; then
        # shellcheck disable=SC2128
        optn=$opt
      else
        # shellcheck disable=SC2015
        [[ -z "$optk" ]] && ( declare -F showOptValWarn &>/dev/null && showOptValWarn "--$optn" ) || declare "$optn=true"
        # shellcheck disable=SC2128
        optn=$opt
      fi

      if [[ ! $SUPPORTED_OPTS\  =~ !?$optn\  ]] ; then
        declare -F showOptWarn &>/dev/null && showOptWarn "--${optn//_/-}"
        shift && continue
      fi

      if [[ ${BASH_REMATCH[0]:0:1} == "!" ]] ; then
        declare "$optn=true" ; unset optn ; optk=true
      else
        unset optk
      fi

      shift && continue
    fi
  else
    if [[ -n "$optn" ]] ; then
      # shellcheck disable=SC2015
      [[ -n "${!optn}" && $MERGEABLE_OPTS\  =~ $optn\  ]] && declare "$optn=${!optn} $1" || declare "$optn=$1"

      unset optn && shift && continue
    fi
  fi

  optt+=("$1") ; shift
done

[[ -n "$optn" ]] && declare "$optn=true"

unset opt optn optm optk

# shellcheck disable=SC2015,SC2086
[[ -n "$KEEP_OPTS" ]] && main $optv || main "${optt[@]}"

################################################################################
