name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  Shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check scripts with Shellcheck
        uses: essentialkaos/shellcheck-action@v1
        with:
          files: SOURCES/web-utils

  Perfecto:
    name: Perfecto
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        if: ${{ env.DOCKERHUB_USERNAME != '' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check spec with Perfecto
        uses: essentialkaos/perfecto-action@v1
        with:
          files: web-utils.spec

  Hadolint:
    name: Hadolint
    runs-on: ubuntu-latest

    needs: Shellcheck

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check dockerfiles with Hadolint
        uses: essentialkaos/hadolint-action@v1
        with:
          files: Dockerfile

  DockerBuild:
    name: Docker Build Check
    runs-on: ubuntu-latest

    needs: Hadolint

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        if: ${{ env.DOCKERHUB_USERNAME != '' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -f Dockerfile -t final-image .

      - name: Measure image size
        run: |
          image_size=$(docker inspect -f "{{ .Size }}" final-image)
          printf "\033[1mUncompressed image size:\033[0m %d (%s)\n" $image_size $(echo "$image_size" | numfmt --to=si)
